# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: answerme_development
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: postgresql
  database: answerme
  pool: 5
  timeout: 5000
  username: root
  password:

test:
  adapter: postgresql
  database: answerme_test
  pool: 5
  timeout: 5000
  username: root
  password: